-- Customer bookings and dispatch. Run after partner_schema.sql.
-- Only the backend (direct Postgres connection) touches these tables:
-- RLS is on with no policies, so the public anon key cannot read or write them.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  role text not null check (role in ('CUSTOMER','ADMIN','DRIVER')),
  full_name text,
  phone text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  booking_ref text not null unique,
  customer_id bigint not null references public.users(id),
  driver_id bigint references public.drivers(id),
  vehicle_id bigint references public.vehicles(id),
  service_type text not null,
  pickup_text text not null,
  drop_text text not null,
  pickup_latitude double precision,
  pickup_longitude double precision,
  drop_latitude double precision,
  drop_longitude double precision,
  route_distance_km double precision,
  tracking_token_hash text,
  driver_status text,
  trip_datetime timestamptz not null,
  car_category text not null,
  estimated_fare double precision,
  final_fare double precision,
  fare_breakdown text,
  status text not null default 'PENDING' check (status in ('PENDING','CONFIRMED','ONGOING','COMPLETED','CANCELLED')),
  customer_note text,
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.booking_status_events (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id),
  old_status text,
  new_status text not null,
  changed_by_user_id bigint references public.users(id),
  note text,
  changed_at timestamptz not null default now()
);

alter table public.vehicles add column if not exists gps_device_id text;
alter table public.drivers add column if not exists push_token text;
create unique index if not exists vehicles_gps_device_idx on public.vehicles(gps_device_id) where gps_device_id is not null;

create index if not exists bookings_status_idx on public.bookings(status);
create index if not exists bookings_trip_datetime_idx on public.bookings(trip_datetime);
create index if not exists bookings_customer_idx on public.bookings(customer_id);
create index if not exists bookings_vehicle_idx on public.bookings(vehicle_id);
create index if not exists booking_status_events_booking_idx on public.booking_status_events(booking_id, id);

alter table public.users enable row level security;
alter table public.bookings enable row level security;
alter table public.booking_status_events enable row level security;
