create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create or replace function public.is_sadakyatra_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = auth.uid() and active = true
  );
$$;

create table if not exists public.partner_applications (
  id bigint generated by default as identity primary key,
  application_ref text not null unique,
  full_name text not null,
  phone text not null,
  vehicle_number text not null,
  vehicle_category text not null check (vehicle_category in ('sedan','suv','traveller')),
  vehicle_model text not null,
  seats integer,
  driver_name text not null,
  driver_phone text not null,
  city text not null,
  operating_area text not null,
  phone_verified boolean not null default false,
  rc_document_key text,
  dl_document_key text,
  insurance_document_key text,
  status text not null default 'PENDING' check (status in ('PENDING','APPROVED','REJECTED')),
  review_note text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.partners (
  id bigint generated by default as identity primary key,
  partner_ref text not null unique,
  application_id bigint not null unique references public.partner_applications(id),
  full_name text not null,
  phone text not null,
  city text not null,
  operating_area text not null,
  backend_partner_id integer,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.drivers (
  id bigint generated by default as identity primary key,
  partner_id bigint not null references public.partners(id),
  driver_name text not null,
  phone text not null unique,
  access_token_hash text not null unique,
  backend_driver_id integer,
  is_active boolean not null default true,
  is_online boolean not null default false,
  latitude double precision,
  longitude double precision,
  location_updated_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.vehicles (
  id bigint generated by default as identity primary key,
  cab_ref text not null unique,
  plate_no text not null unique,
  category text not null check (category in ('sedan','suv','traveller')),
  model text not null,
  seats integer,
  partner_id bigint not null references public.partners(id),
  driver_id bigint not null references public.drivers(id),
  backend_vehicle_id integer,
  rc_document_key text,
  dl_document_key text,
  insurance_document_key text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.driver_status_events (
  id bigint generated by default as identity primary key,
  booking_id bigint not null,
  driver_id bigint not null references public.drivers(id),
  status text not null check (status in ('OFFERED','BOOKING_ACCEPTED','BOOKING_REJECTED','GOING_TO_PICKUP','ARRIVED','TRIP_STARTED','TRIP_COMPLETED')),
  created_at timestamptz not null default now()
);

create index if not exists partner_applications_status_created_idx on public.partner_applications(status, created_at);
create index if not exists drivers_online_active_idx on public.drivers(is_online, is_active);
create index if not exists vehicles_partner_active_idx on public.vehicles(partner_id, active);
create index if not exists driver_status_booking_idx on public.driver_status_events(booking_id, id);

alter table public.admin_users enable row level security;
alter table public.partner_applications enable row level security;
alter table public.partners enable row level security;
alter table public.drivers enable row level security;
alter table public.vehicles enable row level security;
alter table public.driver_status_events enable row level security;

drop policy if exists "Admins read own roster row" on public.admin_users;
create policy "Admins read own roster row" on public.admin_users
  for select to authenticated using (user_id = auth.uid());

drop policy if exists "Admins manage applications" on public.partner_applications;
create policy "Admins manage applications" on public.partner_applications
  for all to authenticated using (public.is_sadakyatra_admin()) with check (public.is_sadakyatra_admin());

drop policy if exists "Admins manage partners" on public.partners;
create policy "Admins manage partners" on public.partners
  for all to authenticated using (public.is_sadakyatra_admin()) with check (public.is_sadakyatra_admin());

drop policy if exists "Admins manage drivers" on public.drivers;
create policy "Admins manage drivers" on public.drivers
  for all to authenticated using (public.is_sadakyatra_admin()) with check (public.is_sadakyatra_admin());

drop policy if exists "Admins manage vehicles" on public.vehicles;
create policy "Admins manage vehicles" on public.vehicles
  for all to authenticated using (public.is_sadakyatra_admin()) with check (public.is_sadakyatra_admin());

drop policy if exists "Admins manage driver events" on public.driver_status_events;
create policy "Admins manage driver events" on public.driver_status_events
  for all to authenticated using (public.is_sadakyatra_admin()) with check (public.is_sadakyatra_admin());

insert into storage.buckets (id, name, public)
values ('partner-documents', 'partner-documents', false)
on conflict (id) do nothing;

drop policy if exists "Admins upload private partner documents" on storage.objects;
create policy "Admins upload private partner documents" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'partner-documents' and public.is_sadakyatra_admin());
drop policy if exists "Admins read private partner documents" on storage.objects;
create policy "Admins read private partner documents" on storage.objects
  for select to authenticated
  using (bucket_id = 'partner-documents' and public.is_sadakyatra_admin());

  create or replace function public.approve_partner_application(
    p_application_id bigint,
    p_partner_ref text,
    p_driver_token_hash text,
    p_rc_document_key text,
    p_dl_document_key text,
    p_insurance_document_key text
  )
  returns jsonb
  language plpgsql
  security definer
  set search_path = public
  as $$
  declare
    application public.partner_applications%rowtype;
    new_partner_id bigint;
    new_driver_id bigint;
    new_vehicle_id bigint;
    new_cab_ref text;
  begin
    select * into application
    from public.partner_applications
    where id = p_application_id and status = 'PENDING'
    for update;
    if not found then raise exception 'Only pending applications can be approved'; end if;

    insert into public.partners (partner_ref, application_id, full_name, phone, city, operating_area)
    values (p_partner_ref, application.id, application.full_name, application.phone, application.city, application.operating_area)
    returning id into new_partner_id;

    insert into public.drivers (partner_id, driver_name, phone, access_token_hash)
    values (new_partner_id, application.driver_name, application.driver_phone, p_driver_token_hash)
    returning id into new_driver_id;

    new_vehicle_id := nextval(pg_get_serial_sequence('public.vehicles', 'id'));
    new_cab_ref := 'SY-CAB-' || lpad(new_vehicle_id::text, 6, '0');
    insert into public.vehicles (
      id, cab_ref, plate_no, category, model, seats, partner_id, driver_id,
      rc_document_key, dl_document_key, insurance_document_key
    ) values (
      new_vehicle_id, new_cab_ref, application.vehicle_number, application.vehicle_category, application.vehicle_model,
      application.seats, new_partner_id, new_driver_id,
      p_rc_document_key, p_dl_document_key, p_insurance_document_key
    ) returning id into new_vehicle_id;

    new_cab_ref := 'SY-CAB-' || lpad(new_vehicle_id::text, 6, '0');
    update public.vehicles set cab_ref = new_cab_ref where id = new_vehicle_id;
    update public.partner_applications
    set status = 'APPROVED', phone_verified = true,
        rc_document_key = p_rc_document_key,
        dl_document_key = p_dl_document_key,
        insurance_document_key = p_insurance_document_key,
        reviewed_at = now()
    where id = application.id;

    return jsonb_build_object('partnerId', new_partner_id, 'driverId', new_driver_id,
      'vehicleId', new_vehicle_id, 'cabRef', new_cab_ref);
  end;
  $$;

  -- Functions are executable by PUBLIC by default; restrict this one to the backend.
  revoke execute on function public.approve_partner_application(bigint, text, text, text, text, text) from public, anon, authenticated;
  grant execute on function public.approve_partner_application(bigint, text, text, text, text, text) to service_role;
